[package]
name = "tsc-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
git2 = "0.19.0"
keyring = { version = "3.5.0", features = ["apple-native"] }
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
serde_json = "1.0.132"
